name: Metrics (languages)

on:
  schedule:
    - cron: '0 6 * * *'   # todos los días 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate languages (most-used)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          base: ""                # no otros módulos
          plugin_languages: yes
          plugin_languages_limit: 8
          # plugin_languages_ignored: html, css
          # plugin_languages_threshold: 2%
          # plugin_languages_details: bytes-size, percentage

