- name: Generate languages (recently-used)
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.languages.recent.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_languages: yes
    plugin_languages_sections: recently-used
    plugin_languages_details: bytes-size, percentage
    plugin_languages_recent_load: 400    # nยบ de eventos a mirar
    plugin_languages_recent_days: 14     # ventana temporal
